# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f22f98d1d96317e2ef51c40a8438f05114e3ed1a54c0e648825d6ff30bef63bc76a1728b78a728627fdb2bca3f456c60f4e031289eb49129a09b7dcef915a0

test:
  secret_key_base: 23c97df375b759fa3bfeaf3f6cb20758036e23a6dd2194f18478f694e37bbf94c1f27228d350cbb2f228f5856bbaf38775ab07e2b3b7fd4f8427fab2157621bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
